<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dashboard</name>
   <tag></tag>
   <elementGuidId>214d529c-26ee-4dac-bd51-26f37f5720b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5356ce0c-c337-4df3-b3c3-d32fbbfb4af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>1c73d971-27eb-4279-b3b4-62c456e27cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>83949221-59cc-4c9e-b813-0458a4cbd724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BoardsTemplatesHomeWorkspacesTTrello WorkspaceBoardsHighlightsViewsMembersSettingsTry Trello PremiumGet unlimited boards, all the views, unlimited automation, and more. Start free trialMost popular templatesGet going faster with a template from the Trello community or choose a categoryTemplateProject ManagementTemplateKanban TemplateTemplateSimple Project BoardTemplateRemote Team HubBrowse the full template galleryYOUR WORKSPACESTTrello WorkspaceBoardsViewsMembers (1)SettingsUpgradeCreate new boardGUEST WORKSPACESBINARBinar Mini ProjectView all closed boards</value>
      <webElementGuid>0cca7a3a-e837-4064-9922-259f4f654fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)</value>
      <webElementGuid>3171b089-9340-4151-8af4-5928d53dcbe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='content']</value>
      <webElementGuid>281b2422-77ce-402a-b994-82850b13f777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div[2]</value>
      <webElementGuid>bdf190c4-abef-452a-af48-a6be937f3373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New stuff!'])[1]/following::div[18]</value>
      <webElementGuid>053d2b9c-302b-4ed8-8f3d-a63146b29cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[1]/following::div[20]</value>
      <webElementGuid>5fcc59a7-d705-48ca-b5bc-e417cd6e2b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[2]/div[2]</value>
      <webElementGuid>c2e6c873-c59a-4d7d-a8cf-2feeeeee837e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'content' and (text() = 'BoardsTemplatesHomeWorkspacesTTrello WorkspaceBoardsHighlightsViewsMembersSettingsTry Trello PremiumGet unlimited boards, all the views, unlimited automation, and more. Start free trialMost popular templatesGet going faster with a template from the Trello community or choose a categoryTemplateProject ManagementTemplateKanban TemplateTemplateSimple Project BoardTemplateRemote Team HubBrowse the full template galleryYOUR WORKSPACESTTrello WorkspaceBoardsViewsMembers (1)SettingsUpgradeCreate new boardGUEST WORKSPACESBINARBinar Mini ProjectView all closed boards' or . = 'BoardsTemplatesHomeWorkspacesTTrello WorkspaceBoardsHighlightsViewsMembersSettingsTry Trello PremiumGet unlimited boards, all the views, unlimited automation, and more. Start free trialMost popular templatesGet going faster with a template from the Trello community or choose a categoryTemplateProject ManagementTemplateKanban TemplateTemplateSimple Project BoardTemplateRemote Team HubBrowse the full template galleryYOUR WORKSPACESTTrello WorkspaceBoardsViewsMembers (1)SettingsUpgradeCreate new boardGUEST WORKSPACESBINARBinar Mini ProjectView all closed boards')]</value>
      <webElementGuid>f21e60ec-2cb1-4ac5-b98e-5b74534e84e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
