<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Set due date reminder_css-191o3mb</name>
   <tag></tag>
   <elementGuidId>df2749ba-4126-4032-a5ff-00d8f95eba3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5de4fd8a-310e-4f8a-9fa4-758789b6930d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-191o3mb</value>
      <webElementGuid>6a9276af-76cd-41d1-b163-afe9f97335b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;theme-dark&quot;]/body[@class=&quot;feplat3731 window-up&quot;]/div[@class=&quot;atlaskit-portal-container&quot;]/div[@class=&quot;atlaskit-portal&quot;]/section[@class=&quot;JpK+-eghInruBP js-react-root&quot;]/div[@class=&quot;gJnViNu1Yqy4Og pt-0&quot;]/div[@class=&quot;js-react-root&quot;]/form[1]/label[1]/div[1]/div[@class=&quot;nch-select F924cc-zqg7LLy css-2b097c-container&quot;]/div[1]/div[@class=&quot;J+c2IiaNOYgZBB _23YWN6zfbb4Ryi css-e41s8j-control&quot;]/div[@class=&quot;css-191o3mb&quot;]</value>
      <webElementGuid>8db2b51e-2822-4e42-beba-2c3c3de306aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/div/div/div[2]</value>
      <webElementGuid>91a3d7d8-df17-4c03-88e6-c680d1a83673</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
