<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_id-checklist</name>
   <tag></tag>
   <elementGuidId>e453e3a8-5a37-4ec9-92de-8da4a7dc4475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-checklist</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-checklist']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7a0095f-fcce-437c-b3d8-2e9afdf665ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-checklist</value>
      <webElementGuid>01366eb8-ae81-4404-8b3f-446ac9192603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-checklist-title js-autofocus</value>
      <webElementGuid>74c1bc23-b190-4718-b4c3-393d592f9275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8594a5f-9326-4182-83e1-1ec71763ca89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checklist</value>
      <webElementGuid>59bd1cc5-0067-4404-87d9-7ec122906756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-default</name>
      <type>Main</type>
      <value>Checklist</value>
      <webElementGuid>59695a9a-4961-410f-aefd-d5ce1f85ab58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>6642e3ff-be24-4591-9b6d-fcd115160fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>f2ed962e-0cb1-48ab-aa8d-8635ca535071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-checklist&quot;)</value>
      <webElementGuid>a7daff76-00d3-4eb5-9718-0fc27b61a047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-checklist']</value>
      <webElementGuid>4bf2e390-0ccc-4e86-bff0-d8572527b479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div/div[2]/div/div/div/form/input</value>
      <webElementGuid>ff03ed6b-c223-4c34-9d81-acb4e9e51d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/input</value>
      <webElementGuid>7bb92517-a1a5-456c-80ea-393a2580bab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-checklist' and @type = 'text']</value>
      <webElementGuid>48d57a3d-fb2f-4395-bd5c-d1dcf1bf1b48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
