<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_name</name>
   <tag></tag>
   <elementGuidId>f3583f4d-628c-4faf-8904-e3c72c9098a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labelName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='labelName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0963d42-7407-4800-87da-3c4341967a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labelName</value>
      <webElementGuid>ad93b529-796e-4147-ab94-edf723d5dcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-autofocus js-label-name</value>
      <webElementGuid>748da16c-bb59-4485-8458-d177bf91487b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1beeff3-fd26-4be1-be86-8cbc55c00918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>77b69548-0b1f-4606-b0a8-2b3bb7aa50c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labelName&quot;)</value>
      <webElementGuid>ccd57e54-0cd7-4c1e-bda4-3c903be185b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='labelName']</value>
      <webElementGuid>cec84265-8620-44cf-936e-cf85f7bca23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div/div[2]/div/div/form/input</value>
      <webElementGuid>a6898ee7-a830-4acf-bc02-26327a1de1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/input</value>
      <webElementGuid>96961d00-8c8d-4409-ae1d-4d6b7ecfa1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'labelName' and @type = 'text' and @name = 'name']</value>
      <webElementGuid>614af3ca-6f15-4c5a-84b1-c951130134ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
