<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dates</name>
   <tag></tag>
   <elementGuidId>8c2263e8-614e-40f7-9eb1-6df06ed4a81e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.qdBhyE-oxlFNZn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chrome-container']/div[3]/div/div/div/div[5]/div[2]/div/div/div/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7fd054d-5b95-4ca1-8620-c10066cb1d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qdBhyE-oxlFNZn</value>
      <webElementGuid>9133dfa5-7ea0-4c06-a19c-ca57bff97231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dates</value>
      <webElementGuid>75aae808-8b95-4923-b405-451a1a34c8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;window-overlay&quot;]/div[@class=&quot;window&quot;]/div[@class=&quot;window-wrapper js-autofocus js-tab-parent&quot;]/div[@class=&quot;card-detail-window u-clearfix&quot;]/div[@class=&quot;window-sidebar&quot;]/div[@class=&quot;window-module u-clearfix&quot;]/div[@class=&quot;u-clearfix&quot;]/div[@class=&quot;js-date-range-picker button-link-container&quot;]/div[@class=&quot;js-react-root&quot;]/button[@class=&quot;v0JKKt7v8pr-4s Ts+YceGnvTbKoG JIXQq8gDYY04N6&quot;]/span[@class=&quot;qdBhyE-oxlFNZn&quot;]</value>
      <webElementGuid>8d94e114-44ac-4530-88aa-1879fad288e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[3]/div/div/div/div[5]/div[2]/div/div/div/button/span[2]</value>
      <webElementGuid>68ced0e7-236a-45e8-a622-acafedf10ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checklist'])[1]/following::span[3]</value>
      <webElementGuid>d21af895-5e34-4836-b34d-ed454a7278d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[2]/following::span[5]</value>
      <webElementGuid>09e1e4f9-f758-4fb3-8f5c-7e3cc28f2f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::span[2]</value>
      <webElementGuid>57040ae0-9947-4f3a-ad2b-8deb1932dd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cover'])[2]/preceding::span[4]</value>
      <webElementGuid>6b0bcb08-c74a-403b-8410-a818d31a54b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dates']/parent::*</value>
      <webElementGuid>1f991f28-be59-434e-a113-9469f8a0dcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/span[2]</value>
      <webElementGuid>d230d438-44fa-42ba-b313-2aaa34249282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Dates' or . = 'Dates')]</value>
      <webElementGuid>fc3e458b-b889-495d-8f7b-707d4de39fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
