<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AUTOMATED</name>
   <tag></tag>
   <elementGuidId>853c674e-8d1b-403d-a43d-558df65c338a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.card-label.mod-selectable.card-label-red.js-select-label.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chrome-container']/div[4]/div/div[2]/div/div/div/div[2]/ul/li[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a78b73d7-a203-4328-ae28-ed55d6e5d429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-label mod-selectable card-label-red js-select-label selected</value>
      <webElementGuid>956f9dd4-edbd-4e51-916f-d17e7f13a111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idlabel</name>
      <type>Main</type>
      <value>62e36289a70fbaa9f270f1c1</value>
      <webElementGuid>913b33fa-b89c-4883-96c0-f1ea5820ff57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>red</value>
      <webElementGuid>a96baf42-75f1-41e3-b814-f6d043a36439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUTOMATED</value>
      <webElementGuid>5978e95b-90de-4db1-8e02-6d3b206667dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;pop-over is-shown&quot;]/div[@class=&quot;no-back&quot;]/div[2]/div[@class=&quot;pop-over-content js-pop-over-content u-fancy-scrollbar js-tab-parent&quot;]/div[1]/div[1]/div[@class=&quot;pop-over-section&quot;]/ul[@class=&quot;edit-labels-pop-over js-labels-list&quot;]/li[4]/span[@class=&quot;card-label mod-selectable card-label-red js-select-label selected&quot;]</value>
      <webElementGuid>0278236e-55b7-49f7-af8d-56fd15b551e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div/div[2]/div/div/div/div[2]/ul/li[4]/span</value>
      <webElementGuid>6cb81b58-24db-4b1f-83c5-614077499759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Labels'])[4]/following::span[7]</value>
      <webElementGuid>b7b60de0-2b12-40ff-bfea-f6ca1fba99c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggested'])[2]/following::span[7]</value>
      <webElementGuid>cb34e6f0-9f87-4a17-9aa6-d2ab2bbfe8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a new label'])[1]/preceding::span[6]</value>
      <webElementGuid>6571ccfc-a025-44b0-a287-6e2390b45750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show more labels'])[1]/preceding::span[6]</value>
      <webElementGuid>3e96ca01-8d43-43b2-8dd1-242c9f10e836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUTOMATED']/parent::*</value>
      <webElementGuid>bb811124-f261-445c-ae47-412dd7e8f806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span</value>
      <webElementGuid>54124ed6-7d20-465e-84fa-fc9fdcb4843c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'AUTOMATED' or . = 'AUTOMATED')]</value>
      <webElementGuid>ab965fc8-4d9e-4db4-8098-5c1e327d4d23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
