<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To Do_nch-button nch-button--primary _69b742</name>
   <tag></tag>
   <elementGuidId>28920870-cfb3-44ff-beb1-5af20d5d265c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.nch-button.nch-button--primary.confirm.mod-compact.js-add-card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Add card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfdf891b-c952-459b-b33b-e5395156286e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nch-button nch-button--primary confirm mod-compact js-add-card</value>
      <webElementGuid>cebb12ea-5e7e-46e0-bb99-aa7ef03525e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9e4541e2-502c-4423-9778-bdbb3245fe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add card</value>
      <webElementGuid>8339d6a7-57b0-43d0-b782-bc3f7d922183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/div[@class=&quot;js-list list-wrapper&quot;]/div[@class=&quot;list js-list-content&quot;]/div[@class=&quot;list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable&quot;]/div[@class=&quot;card-composer&quot;]/div[@class=&quot;cc-controls u-clearfix&quot;]/div[@class=&quot;cc-controls-section&quot;]/input[@class=&quot;nch-button nch-button--primary confirm mod-compact js-add-card&quot;]</value>
      <webElementGuid>ba05d04f-2d5d-4965-b39d-df433cbdb6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11e2c247-bac0-40d2-bae9-273842a03835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nch-button nch-button--primary confirm mod-compact js-add-card</value>
      <webElementGuid>bbad115e-c705-414e-a941-54725cb9ce64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8663f276-e053-4635-b088-9d6b7c1f08b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add card</value>
      <webElementGuid>2b16007d-90bf-4ec9-bf23-5d2b204a0502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/div[@class=&quot;js-list list-wrapper&quot;]/div[@class=&quot;list js-list-content&quot;]/div[@class=&quot;list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable&quot;]/div[@class=&quot;card-composer&quot;]/div[@class=&quot;cc-controls u-clearfix&quot;]/div[@class=&quot;cc-controls-section&quot;]/input[@class=&quot;nch-button nch-button--primary confirm mod-compact js-add-card&quot;]</value>
      <webElementGuid>3a8b0b1b-bc2f-4177-947e-270730521913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Add card']</value>
      <webElementGuid>f99d465b-c2fc-4c80-be65-249e22f31621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='board']/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>133cd142-7d3c-47a4-bb1e-2c6a28d255ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>fed0ad98-5950-44c6-8aa1-ce7c3beb7678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>eed5165f-73fa-4b1b-b3be-9491e0a2a265</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
