<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Position_nch-button nch-button--prima_29d907</name>
   <tag></tag>
   <elementGuidId>dd0a2ca5-1040-4018-9906-f541ec862e0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.nch-button.nch-button--primary.wide.js-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Move']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a89e5938-6bb2-4c8d-b5b7-e140f954d96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nch-button nch-button--primary wide js-submit</value>
      <webElementGuid>416dfbaf-f55f-42a6-9a21-b992fffba097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ee1698cc-d93a-4269-9cc0-6ad8ba5982bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>a34213a3-bfc3-4f0d-937d-6c40618de1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;pop-over is-shown&quot;]/div[@class=&quot;no-back&quot;]/div[2]/div[@class=&quot;pop-over-content js-pop-over-content u-fancy-scrollbar js-tab-parent&quot;]/div[1]/div[1]/div[@class=&quot;pop-over-section&quot;]/input[@class=&quot;nch-button nch-button--primary wide js-submit&quot;]</value>
      <webElementGuid>b1aeea56-dc6e-4521-9582-3de6e5fbc669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Move']</value>
      <webElementGuid>976ab56b-1a16-4ea6-8a72-ee18499e9a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>8b71ed7b-0b50-48fb-870c-d4d7e9d74458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>275ae3ad-5595-4cba-a4dd-75889e2eb347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>afe41562-908c-416a-93a9-e2f14d335168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
