<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_4NEW Test 2</name>
   <tag></tag>
   <elementGuidId>0a546cff-32d0-48d8-bde3-8660a4a5afed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.list-card-title.js-card-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='board']/div/div/div[2]/a/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>761d84ca-c529-4f35-9e6d-12a98351aa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-card-title js-card-name</value>
      <webElementGuid>a0549753-8ae1-4cea-bd7d-5283ec402a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>ee6c5fcc-e8bd-450a-b001-fb5171d19f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#4NEW Test 2</value>
      <webElementGuid>2ea18cec-f250-46f8-b4f3-c0f4cbf906f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/div[@class=&quot;js-list list-wrapper&quot;]/div[@class=&quot;list js-list-content&quot;]/div[@class=&quot;list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable&quot;]/a[@class=&quot;list-card js-member-droppable ui-droppable ui-sortable-handle active-card&quot;]/div[@class=&quot;list-card-details js-card-details&quot;]/span[@class=&quot;list-card-title js-card-name&quot;]</value>
      <webElementGuid>0829430d-a12a-4603-9f3c-9f1e39ce6917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='board']/div/div/div[2]/a/div[3]/span</value>
      <webElementGuid>e19ff9fa-4e14-462f-87f5-400480dab458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Do'])[2]/following::span[5]</value>
      <webElementGuid>bed8377b-38a3-49eb-93a0-32f3f43c18c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Do'])[1]/following::span[5]</value>
      <webElementGuid>946439e2-a0cb-4f2a-9879-f2eae58b3326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a card'])[1]/preceding::span[8]</value>
      <webElementGuid>da6376b1-3480-4791-a787-0b5f53f1fe10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEW Test 2']/parent::*</value>
      <webElementGuid>5c6e885c-c8bb-4a75-9e85-b1b7996eea03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[3]/span</value>
      <webElementGuid>d7a15dbc-2002-4c70-ae9d-9691746badd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '#4NEW Test 2' or . = '#4NEW Test 2')]</value>
      <webElementGuid>a3f1e3bd-4752-4fbd-b4ae-24f0c7f8ce8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
