<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add a card</name>
   <tag></tag>
   <elementGuidId>d9eba6c5-be39-4114-a7ae-e9902c5fc5b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.js-add-a-card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='board']/div/div/div[3]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>847412f9-163e-4ae2-84d1-2e0b9f040531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-add-a-card</value>
      <webElementGuid>e101875c-7ac5-470b-81fe-0d6e40377c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add a card</value>
      <webElementGuid>7d0094a0-db41-4154-8d58-c2dee5882250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/div[@class=&quot;js-list list-wrapper&quot;]/div[@class=&quot;list js-list-content&quot;]/div[@class=&quot;card-composer-container js-card-composer-container&quot;]/a[@class=&quot;open-card-composer js-open-card-composer&quot;]/span[@class=&quot;js-add-a-card&quot;]</value>
      <webElementGuid>456c1f76-a618-4429-94ae-178c1acf105b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='board']/div/div/div[3]/a/span[2]</value>
      <webElementGuid>182be2a8-0687-4f19-aa4b-15aa26e7fe4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Do'])[2]/following::span[5]</value>
      <webElementGuid>c36d70e1-a9b8-42b8-94fa-a432998eb170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Do'])[1]/following::span[5]</value>
      <webElementGuid>1e5731aa-d8d7-4851-be59-a2cfd30d8208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[1]/preceding::span[2]</value>
      <webElementGuid>6a50eb5b-8d70-4921-a49e-2f806f184cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[2]/preceding::span[2]</value>
      <webElementGuid>2de666a0-5f9c-4d6b-a772-1adb8d8bb372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add a card']/parent::*</value>
      <webElementGuid>3790762b-27be-45e5-9e14-d2ad60a76d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/a/span[2]</value>
      <webElementGuid>e9b8391b-65cf-4d6a-98e5-428f61478c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add a card' or . = 'Add a card')]</value>
      <webElementGuid>d1178c75-b01d-4b37-943e-d336c71142a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
