<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_To Do_list-card-composer-textarea _714487</name>
   <tag></tag>
   <elementGuidId>d7c6b978-bda8-4b36-99a5-198ee6e7ae60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.list-card-composer-textarea.js-card-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='board']/div/div/div[2]/div/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d1c7cdc8-a38b-4544-a169-1649757c9d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-card-composer-textarea js-card-title</value>
      <webElementGuid>4ff8222f-94cc-4380-8942-6716e18271c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>57685bbd-98e0-43bf-a6bf-95d558264c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a title for this card…</value>
      <webElementGuid>fe183d5d-a925-40c9-9cf6-b62a12052d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autosize</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aca0cb80-dd60-4359-a0bf-d74c27d7985c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/div[@class=&quot;js-list list-wrapper&quot;]/div[@class=&quot;list js-list-content&quot;]/div[@class=&quot;list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable&quot;]/div[@class=&quot;card-composer&quot;]/div[@class=&quot;list-card js-composer&quot;]/div[@class=&quot;list-card-details u-clearfix&quot;]/textarea[@class=&quot;list-card-composer-textarea js-card-title&quot;]</value>
      <webElementGuid>6839c37c-326f-4c30-8aac-fd7f6803528c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>58ed4a46-1002-4e99-aed3-546d41ca3041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-card-composer-textarea js-card-title</value>
      <webElementGuid>a29ca924-ab09-4700-987d-53258efd56d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4b3b1d14-6784-4680-a5a5-bc03f1f937cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a title for this card…</value>
      <webElementGuid>b7c36863-91fb-41e2-9537-25d014b1c023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autosize</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25491ec3-8ce4-43e7-ae26-b3170be53c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)/div[@class=&quot;js-list list-wrapper&quot;]/div[@class=&quot;list js-list-content&quot;]/div[@class=&quot;list-cards u-fancy-scrollbar u-clearfix js-list-cards js-sortable ui-sortable&quot;]/div[@class=&quot;card-composer&quot;]/div[@class=&quot;list-card js-composer&quot;]/div[@class=&quot;list-card-details u-clearfix&quot;]/textarea[@class=&quot;list-card-composer-textarea js-card-title&quot;]</value>
      <webElementGuid>b99b286a-2288-4a3c-85a3-4c89fcc6a8c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='board']/div/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>cd2fcd52-fd2e-4f05-a0fd-77bdd70b254f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>e445ba37-9cc4-4cbd-be1d-633c68fdd376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter a title for this card…']</value>
      <webElementGuid>83587a2c-a478-4b73-9617-0405f17f8106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
