<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Move</name>
   <tag></tag>
   <elementGuidId>de14c867-1a9f-4708-b564-b03d7435295d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button-link.js-move-card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chrome-container']/div[3]/div/div/div/div[5]/div[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be0c9e54-79d8-4d5a-aa00-7ab1df040eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-link js-move-card</value>
      <webElementGuid>4c94e848-4c8e-48b1-932b-27ef4779acda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c80c13ea-9a2f-43a0-afb5-2be679dedd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>bd6f5a24-95c8-44d8-a713-f48ee6e417f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>e6533179-9965-4432-ba98-02733a9ec174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;window-overlay&quot;]/div[@class=&quot;window&quot;]/div[@class=&quot;window-wrapper js-autofocus js-tab-parent&quot;]/div[@class=&quot;card-detail-window u-clearfix&quot;]/div[@class=&quot;window-sidebar&quot;]/div[@class=&quot;window-module u-clearfix&quot;]/div[@class=&quot;u-clearfix&quot;]/a[@class=&quot;button-link js-move-card&quot;]</value>
      <webElementGuid>7cff6319-deed-4baf-a331-f9face648ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[3]/div/div/div/div[5]/div[5]/div/a</value>
      <webElementGuid>45183096-926a-4e95-849a-52ab0b4a2084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::a[1]</value>
      <webElementGuid>f8b9a3cc-4bb4-4d03-b968-4a4cba58f241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add button'])[1]/following::a[1]</value>
      <webElementGuid>d29f0756-6887-4e41-992e-38cb1b1066c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/preceding::a[1]</value>
      <webElementGuid>e39dee46-aa87-4169-a144-72961bae9315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[57]</value>
      <webElementGuid>30ced350-a695-454e-b5df-19402914d886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[5]/div/a</value>
      <webElementGuid>6dba20ae-e0cd-4592-81a3-24e1a2446f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Move' and (text() = 'Move' or . = 'Move')]</value>
      <webElementGuid>ada49af4-e8c4-45a8-87d0-568df1382d13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
