<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Position_nch-button nch-button--prima_29d907</name>
   <tag></tag>
   <elementGuidId>8faed992-699d-4539-9d08-1e933feeeb94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.nch-button.nch-button--primary.wide.js-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Move']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9c534b3-f846-4658-87e8-3da99df10e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nch-button nch-button--primary wide js-submit</value>
      <webElementGuid>1497704f-dfeb-459b-87e9-c11316f7acab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cd0d98ae-5b87-4701-88dd-e0b21ca0a04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>812789a0-de77-49e4-bfa5-9ef537759875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;pop-over is-shown&quot;]/div[@class=&quot;no-back&quot;]/div[2]/div[@class=&quot;pop-over-content js-pop-over-content u-fancy-scrollbar js-tab-parent&quot;]/div[1]/div[1]/div[@class=&quot;pop-over-section&quot;]/input[@class=&quot;nch-button nch-button--primary wide js-submit&quot;]</value>
      <webElementGuid>d128167c-1c85-4f3a-8a75-cb87d67cf4a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Move']</value>
      <webElementGuid>16719bc1-51a6-48cb-a2aa-10c47294d288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[4]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>286f0409-b084-4523-9f04-02c80d11773c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>27349a50-cc90-491e-8ad0-80b073c312bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>a7d3b801-6e26-4e68-9c45-8f1ae9f66d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
