<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BoardsTemplatesHomeWorkspacesTTrello Wo_add512</name>
   <tag></tag>
   <elementGuidId>9f9a9d6e-c673-4739-a2c9-8abd50cde082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.home-sticky-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9599c06-4d03-414a-a841-69f725b2c234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-sticky-container</value>
      <webElementGuid>b27084c9-8661-4b67-9fdc-c59285e0cb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BoardsTemplatesHomeWorkspacesTTrello WorkspaceBoardsHighlightsViewsMembersSettingsYOUR WORKSPACESTTrello WorkspaceBoardsViewsMembers (1)SettingstesTesting AUTOMATIONCreate new boardGUEST WORKSPACESBINARBinar Mini ProjectView all closed boards</value>
      <webElementGuid>429f6987-6de9-447a-8288-db80366a6e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;member-boards-view&quot;]/div[@class=&quot;js-boards-page&quot;]/div[@class=&quot;js-react-root&quot;]/div[1]/div[@class=&quot;home-container&quot;]/div[@class=&quot;home-sticky-container&quot;]</value>
      <webElementGuid>c19f22b7-2c93-4238-814e-cd4591501d38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div/div/div/div</value>
      <webElementGuid>897adcdc-619d-45d0-9100-11e2cd97e148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New stuff!'])[1]/following::div[24]</value>
      <webElementGuid>2deeb805-0e86-45ac-b418-6424b423a739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[1]/following::div[26]</value>
      <webElementGuid>fd0f6c1d-5afe-464b-ade5-7010a7d3132f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div</value>
      <webElementGuid>07b82344-2f92-4367-8257-dd3d24188039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BoardsTemplatesHomeWorkspacesTTrello WorkspaceBoardsHighlightsViewsMembersSettingsYOUR WORKSPACESTTrello WorkspaceBoardsViewsMembers (1)SettingstesTesting AUTOMATIONCreate new boardGUEST WORKSPACESBINARBinar Mini ProjectView all closed boards' or . = 'BoardsTemplatesHomeWorkspacesTTrello WorkspaceBoardsHighlightsViewsMembersSettingsYOUR WORKSPACESTTrello WorkspaceBoardsViewsMembers (1)SettingstesTesting AUTOMATIONCreate new boardGUEST WORKSPACESBINARBinar Mini ProjectView all closed boards')]</value>
      <webElementGuid>b18bd141-ae97-44e7-84a8-dcedd5fdb3aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
